name: Checkers
version: 0.1.0.0
github: "chiyoku/Checkers"
license: BSD3
author: "Felipe G"
maintainer: "chiyokuoni@gmail.com"
copyright: "2022 Felipe G"

description: Please see the README on GitHub at <https://github.com/githubuser/Checkers#readme>

dependencies:
  - base >= 4.7 && < 5

default-extensions:
  - GADTs
  - DataKinds
  - KindSignatures
  - LambdaCase
  - GeneralisedNewtypeDeriving
  - StandaloneDeriving
  - FlexibleContexts
  - MultiWayIf
  - TupleSections
  - ConstraintKinds
  - StrictData
  - OverloadedStrings

executables:
  Checkers-exe:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mtl
      - megaparsec
      - text
      - ansi-terminal